name: Test

on:
  pull_request:
  push:
    branches: [main, beta, vrchat-relay]

jobs:
  ci:
    runs-on: [self-hosted, Linux, docker, buildx]
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: "24"
          package-manager-cache: false

      - name: Syntax check
        run: node --check vrchat-relay/vrchat-relay.js
